export const metadata = {
  title: "Terms of Service | Grindx AI",
  description: "Terms of Service for Grindx AI",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8 lg:py-12">
        <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
          <div className="border-b border-slate-200 bg-slate-50/70 px-6 py-8 sm:px-8 sm:py-10">
            <div className="max-w-3xl">
              <p className="text-sm font-medium uppercase tracking-[0.18em] text-slate-500">
                Grindx AI
              </p>
              <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
                Terms of Service
              </h1>
              <p className="mt-3 text-sm text-slate-500 sm:text-base">
                Effective date: 19 April 2026
              </p>
            </div>
          </div>

          <div className="px-6 py-8 sm:px-8 sm:py-10 lg:px-10">
            <div
              className="
                max-w-none text-[15px] leading-7 text-slate-700
                [&_h2]:mt-12 [&_h2]:mb-4 [&_h2]:border-t [&_h2]:border-slate-200 [&_h2]:pt-8
                [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-slate-900
                [&_h2:first-of-type]:mt-0 [&_h2:first-of-type]:border-t-0 [&_h2:first-of-type]:pt-0
                [&_h3]:mt-8 [&_h3]:mb-3 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-slate-900
                [&_p]:my-4
                [&_ul]:my-4 [&_ul]:space-y-2 [&_ul]:pl-6
                [&_li]:pl-1
                [&_strong]:font-semibold [&_strong]:text-slate-900
              "
            >
              <p>
                These Terms of Service (“Terms”) govern your access to and use of
                Grindx AI (“Grindx AI”, “we”, “us”, or “our”), including our
                website, applications, and related services.
              </p>

              <p>
                By accessing or using Grindx AI, you agree to these Terms. If
                you do not agree, do not use the service.
              </p>

              <h2>1. Eligibility and Account Use</h2>
              <p>
                You must use Grindx AI only in compliance with applicable law.
                You are responsible for providing accurate account information and
                for maintaining the security of your account credentials.
              </p>
              <p>
                You are responsible for activity that occurs under your account,
                including uploaded content, submitted questions, and use of study
                features.
              </p>

              <h2>2. Description of the Service</h2>
              <p>
                Grindx AI is an AI-powered study assistant designed to help users
                work with educational content and study materials.
              </p>
              <p>Depending on the plan and available features, Grindx AI may allow users to:</p>
              <ul>
                <li>Upload files such as PDF, Word, text, or image content</li>
                <li>Paste text and submit URLs for analysis</li>
                <li>Generate summaries and key concepts</li>
                <li>Ask grounded questions about uploaded content</li>
                <li>Create practice questions and mock tests</li>
                <li>Use text-to-speech and related audio features</li>
                <li>Sync documents and chat history across devices</li>
              </ul>

              <h2>3. Educational Use Only</h2>
              <p>
                Grindx AI is provided as a learning and productivity tool for
                general educational use. It does not guarantee academic results,
                professional advice, or perfect accuracy.
              </p>
              <p>
                You are responsible for reviewing, verifying, and applying any
                summaries, explanations, answers, quizzes, mock tests, or other
                outputs generated by the service.
              </p>

              <h2>4. AI-Generated Content Disclaimer</h2>
              <p>
                Grindx AI uses AI systems to process content and generate outputs.
                AI-generated responses may be incomplete, inaccurate, outdated,
                misleading, or unsuitable for your particular needs.
              </p>
              <p>
                You should not rely solely on AI-generated content for academic,
                legal, financial, medical, compliance, or other high-stakes
                decisions.
              </p>

              <h2>5. Your Content</h2>
              <p>
                You may submit content to Grindx AI, including uploaded
                documents, images, pasted text, URLs, chat messages, and other
                study material (“User Content”).
              </p>
              <p>
                You retain your rights in your User Content. However, you are
                solely responsible for the content you submit and for ensuring
                that you have the right to use and share it.
              </p>
              <p>You must not submit content that:</p>
              <ul>
                <li>Violates any law or regulation</li>
                <li>Infringes another person’s intellectual property or privacy rights</li>
                <li>Contains malicious code, harmful material, or abusive content</li>
                <li>Is fraudulent, deceptive, or intended to misuse the service</li>
              </ul>

              <h2>6. Acceptable Use</h2>
              <p>You agree not to misuse Grindx AI. This includes, without limitation, attempting to:</p>
              <ul>
                <li>Interfere with, disrupt, or overload the service</li>
                <li>Gain unauthorized access to accounts, systems, or data</li>
                <li>Reverse engineer, probe, scrape, or exploit the platform improperly</li>
                <li>Bypass limits, pricing rules, subscriptions, or trial controls</li>
                <li>Use the service for unlawful, abusive, or fraudulent purposes</li>
                <li>Upload or distribute harmful software, spam, or malicious content</li>
              </ul>

              <h2>7. Plans, Trials, Billing, and Subscription Terms</h2>
              <p>
                Grindx AI may offer free and paid plans, including trial access,
                subscription-based access, and feature differences between plans.
              </p>
              <p>
                Paid plans, billing, renewals, cancellations, and related payment
                processing may be handled through third-party payment providers
                such as Stripe.
              </p>
              <p>
                By starting a paid subscription or trial, you authorize the
                applicable billing and payment processing needed to provide the
                service.
              </p>
              <ul>
                <li>Plan features and limits may vary by subscription tier</li>
                <li>Trials may be limited to eligible users only</li>
                <li>Subscription pricing may change in the future</li>
                <li>Cancellation may take effect at the end of the current billing period unless stated otherwise</li>
                <li>Access to paid features may end when a subscription or trial ends</li>
              </ul>

              <h2>8. Trial Abuse and Billing Integrity</h2>
              <p>
                To protect billing integrity and prevent misuse of free-trial or
                paid subscription flows, we may apply reasonable anti-abuse
                controls.
              </p>
              <p>
                This may include retaining a minimal identifier, such as an email
                record, after eligible account deletion solely to help prevent
                repeated trial abuse. This does not mean we retain deleted study
                materials for that purpose.
              </p>

              <h2>9. Intellectual Property</h2>
              <p>
                Grindx AI, including its software, branding, design, interface,
                and related materials, is owned by us or our licensors and is
                protected by applicable intellectual property laws.
              </p>
              <p>
                These Terms do not grant you ownership of the service or any
                rights to copy, modify, distribute, sell, or commercially exploit
                the service except as permitted by law or by our written consent.
              </p>

              <h2>10. Service Availability and Changes</h2>
              <p>
                We may modify, suspend, improve, limit, or discontinue any part
                of Grindx AI at any time, with or without notice.
              </p>
              <p>
                We do not guarantee that the service will always be available,
                uninterrupted, secure, or error-free, or that every feature will
                remain available forever.
              </p>

              <h2>11. Suspension and Termination</h2>
              <p>
                We may suspend, restrict, or terminate access to Grindx AI if we
                reasonably believe that you have violated these Terms, misused the
                service, engaged in fraud, created billing risk, failed to pay
                applicable fees, or created legal, operational, or security risk.
              </p>
              <p>
                You may stop using the service at any time. You may also delete
                your account using available account controls where provided.
              </p>

              <h2>12. Privacy</h2>
              <p>
                Your use of Grindx AI is also subject to our Privacy Policy,
                which explains how we collect, use, store, share, and delete
                information.
              </p>

              <h2>13. No Warranty</h2>
              <p>
                To the maximum extent permitted by law, Grindx AI is provided on
                an “as is” and “as available” basis without warranties of any
                kind, whether express, implied, or statutory.
              </p>
              <p>
                We do not warrant that the service will be uninterrupted,
                accurate, reliable, or suitable for any specific purpose.
              </p>

              <h2>14. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, we are not liable for any
                indirect, incidental, special, consequential, exemplary, or loss
                of data, profits, revenue, business, opportunity, goodwill, or
                other similar losses arising from or related to your use of
                Grindx AI.
              </p>
              <p>
                To the maximum extent permitted by law, our total liability for
                claims arising out of or relating to the service will be limited
                to the amount you paid us, if any, for the service during the
                period reasonably related to the claim.
              </p>

              <h2>15. Indemnity</h2>
              <p>
                You agree to indemnify and hold harmless Grindx AI, its owners,
                affiliates, service providers, and personnel from claims,
                liabilities, damages, losses, and expenses arising out of or
                related to your User Content, your misuse of the service, or your
                violation of these Terms or applicable law.
              </p>

              <h2>16. Changes to These Terms</h2>
              <p>
                We may update these Terms from time to time. When we do, we will
                update the effective date above. Your continued use of Grindx AI
                after updated Terms become effective means you accept the revised
                Terms, to the extent permitted by law.
              </p>

              <h2>17. Contact Us</h2>
              <p>
                If you have questions about these Terms, contact:
              </p>

              <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 px-5 py-4 text-slate-700">
                <p className="m-0">
                  <strong>INSIGHTX DATA &amp; AI SOLUTIONS</strong>
                </p>
                <p className="mt-2 mb-0">Email: info@insightxai.com.au</p>
                <p className="mt-2 mb-0">Website: https://grindx.insightxai.com.au</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}